# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

jobs:
  - job: firsttestjob
    displayName: displayforfirsttestjob
    pool: "Hosted Ubuntu 1604"
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: 'echo $PR_NUMBER'
    - script: |
        if [[ -z $PR_NUMBER ]]; then
          NS="not a PR"
        else
          NS="github-pr-$PR_NUMBER"
        fi
    
        echo "Namespace is ${NS}"
