# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more: 
# https://aka.ms/yaml

resources:
  repositories:
  - repository: "keljos/privatemultirepo"
    type: github
    endpoint: "foo"
    name: keljos/privatemultirepo
    
trigger:
- master

pool: 'Default'
#pool:
#  vmImage: 'Ubuntu-16.04'
  
steps:
- checkout: self
- checkout: keljos/privatemultirepo

- script: dir $(Build.SourcesDirectory)
