trigger:
- master
jobs:
- job: publish
  pool: 'default'
  steps:
  - script: |
     cd $(Build.ArtifactStagingDirectory)
     echo "hello world" > hi.txt
     echo "bye" > bye.txt
     mkdir usa
     cd usa
     mkdir nc
     cd nc
     mkdir durham
     cd durham
     echo "hello from Durham" > greeting.txt
    displayName: Create some text files
  - task: PublishPipelineArtifact@0
    displayName: "Publish Artifact: drop"
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: drop
      publishLocation: Container
- job: download
  dependsOn: publish
  condition: succeeded()
  pool: 'default'
  steps:
  - task: DownloadPipelineArtifact@1
    displayName: "Download Pipeline Artifacts"
    inputs:
      artifactName: drop
