jobs:
  - job: firsttestjob
    pool: 'Default'
    steps:
    - task: Maven@2
      inputs:
        mavenPomFile: 'ci-test-app/pom.xml'
        goals: clean
        jdkVersionOption: 1.8
        jdkArchitectureOption: x64
        checkStyleRunAnalysis: false
        pmdRunAnalysis: false
        findBugsRunAnalysis: false
    - task: CopyFiles@2
      displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
      inputs:
        SourceFolder: '$(system.defaultworkingdirectory)'
        Contents: '**/*.jar'
        TargetFolder: '$(build.artifactstagingdirectory)'
      condition: succeededOrFailed()
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: drop'
      inputs:
        PathtoPublish: '$(build.artifactstagingdirectory)'
      condition: succeededOrFailed()
