# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java
pr:
  branches:
    include:
    - test

jobs:
  - job: firsttestjob
    displayName: displayforfirsttestjob
    pool: 'Hosted'
    steps:
- script: |
    if [[ -z ${PR_NUMBER} ]]; then
      NS="not a PR"
    else
      NS="github-pr-${PR_NUMBER}"
    fi
    echo "Namespace is ${NS}"
  env:
    PR_NUMBER: $(System.PullRequest.PullRequestNumber)
