
jobs:
  - job: firsttestjob
    pool: 'Default'
    steps:
    - task: Maven@2
      inputs:
        mavenPomFile: 'ci-test-app/pom.xml'
        jdkVersionOption: 1.8
        jdkArchitectureOption: x64
        checkStyleRunAnalysis: true
        pmdRunAnalysis: true
        findBugsRunAnalysis: true
  - job: secondtestjob
    pool: 'Default'
    steps:
    - task: Maven@2
      inputs:
        mavenPomFile: 'ci-test-app/pom.xml'
        jdkVersionOption: 1.8
        jdkArchitectureOption: x64
        checkStyleRunAnalysis: true
        pmdRunAnalysis: true
        findBugsRunAnalysis: true
        
